apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: sentinella
spec:
  selector:
    matchLabels:
      app: sentinella

  template:
    metadata:
      labels:
        app: sentinella
    spec:
      containers:
        - name: sentinella
          image: REPLACE_WITH_IMAGE_NAME
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx256m -Dconfig.resource=prod-application.conf"
            - name: PLAY_CRYPTO_SECRET
              value: "IcXzqBO+JfQRmdspp6HW8MjOQy62LM3f7dSw5via4z8="
            - name: KAFKA_SERVICE_NAME
              value: "_tcp-clients._tcp.strimzi-kafka-brokers"
            - name: REQUIRED_CONTACT_POINT_NR
              value: "1"
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 0.25
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sentinella
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9000
  selector:
    app: sentinella
  type: LoadBalancer