apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql-simple
  name: postgresql-simple
spec:
  clusterIP: None
  ports:
    - name: web
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgresql-simple
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgresql-simple
  name: postgresql-simple
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: postgresql-simple
  serviceName: postgresql-simple
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgresql-simple
    spec:
      containers:
        - env:
            - name: POSTGRES_USER
              value: simpledb
            - name: POSTGRES_PASSWORD
              value: simpledb
#              valueFrom:
#                secretKeyRef:
#                  name: simple-secret
#                  key: POSTGRES_DB_PASSWORD
            - name: POSTGRES_DB
              value: simpledb
            - name: PGDATA
              value: /pgdata/data
          image: postgres:13.0
          imagePullPolicy: Always
          name: postgresql-simple
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP
          resources:
            requests:
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /pgdata
              name: pgdata
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: postgresql-pvc
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi