apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: simple
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
        - name: simple
          image: REPLACE_WITH_IMAGE_NAME
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx256m -Dconfig.resource=prod-application.conf"
            - name: PLAY_CRYPTO_SECRET
              value: "7p6Oc6N74Svh+57Kd0W/k5dj4lgMJcqPFUwCQ/Dyuu4="
            - name: SIMPLE_DB_URL
              value: "jdbc:postgresql://35.205.131.182/simpledb"
            - name: SIMPLE_DB_USER
              value: simpledb
            - name: SIMPLE_DB_PWD
              valueFrom:
                secretKeyRef:
                  name: simple-secret
                  key: db-password
            - name: REQUIRED_CONTACT_POINT_NR
              value: "1"
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 0.25
              memory: 512Mi
          ports:
            - name: management
              containerPort: 8558
          readinessProbe:
            httpGet:
              path: "/ready"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: simple
spec:
  selector:
    app: simple
  ports:
    - name: http
      port: 9000
      targetPort: 9000
  type: LoadBalancer
