---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fintech-ingress
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/override: https-redirect
    # konghq.com/plugins: zipkin,prometheus,jwt-keycloak
spec:
  tls:
    - hosts:
        - REPLACE_WITH_FQDN
      secretName: REPLACE_WITH_CERT_MANAGER_CERT_NAME
  rules:
    - host: REPLACE_WITH_FQDN
      http:
        paths:
          - path: "/auth"
            backend:
              serviceName: keycloak-http
              servicePort: 80
          - path: "/services"
            backend:
              serviceName: kong-kong-admin
              servicePort: 8001
          - path: "/routes"
            backend:
              serviceName: kong-kong-admin
              servicePort: 8001
          - path: "/plugins"
            backend:
              serviceName: kong-kong-admin
              servicePort: 8001
          - path: "/rest/bucket"
            backend:
              serviceName: bucket
              servicePort: 9000
          - path: "/rest/account"
            backend:
              serviceName: account
              servicePort: 9000
          - path: "/rest/identity"
            backend:
              serviceName: identity
              servicePort: 9000
          - path: "/rest/subscription/identity"
            backend:
              serviceName: subscription-fintech
              servicePort: 9000
          - path: "/rest/subscription/account"
            backend:
              serviceName: subscription-fintech
              servicePort: 9000
          - path: "/rest/subscription/bucket"
            backend:
              serviceName: subscription-fintech
              servicePort: 9000