apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: simple-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: simple.cgn.it
      http:
        paths:
          - path: "/api/conto"
            backend:
              serviceName: simple
              servicePort: 9000
          - path: "/api/versa"
            backend:
              serviceName: simple
              servicePort: 9000
          - path: "/api/preleva"
            backend:
              serviceName: simple
              servicePort: 9000
          - path: "/api/versione"
            backend:
              serviceName: simple
              servicePort: 9000
          - path: "/cluster/members"
            backend:
              serviceName: simple
              servicePort: 8558