---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: simple-ingress
  annotations:
    kubernetes.io/ingress.class: kong
    # konghq.com/override: https-redirect
    # konghq.com/plugins: zipkin,prometheus,jwt-keycloak
spec:
  # tls:
  #   - hosts:
  #       - REPLACE_WITH_FQDN
  #     secretName: REPLACE_WITH_CERT_MANAGER_CERT_NAME
  rules:
    - http:
        paths:
          - path: "/api/conto"
            backend:
              serviceName: simple
              servicePort: 9000
          - path: "/api/versa"
            backend:
              serviceName: simple
              servicePort: 9000
          - path: "/api/preleva"
            backend:
              serviceName: simple
              servicePort: 9000
          - path: "/api/versione"
            backend:
              serviceName: simple
              servicePort: 9000
          - path: "/sentinella/versione"
            backend:
              serviceName: sentinella
              servicePort: 9000
